language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: hhvm

notifications:
  slack: becrafted:x1zECN0tTUYPbeOeXMZ4cw5t
