<?php
/**
 * BongaTech SMS Client Library for PHP.
 *
 * @copyright Copyright (c) 2017
 * @author   Vincent Mosoti <vincent@vmosoti.com>
 * @license https://github.com/VMosoti/bongatech-sms/blob/master/LICENSE
 */

namespace VMosoti\BongaTech;

use VMosoti\BongaTech\Exceptions\BatchTypeNotSetException;

/**
 * Class SMS
 * @package VMosoti\BongaTech
 */
class SMS
{
    /**
     * Version number of the SMS API.
     *
     * @var string
     */
    const VERSION = '1.0';

    /**
     * user ID registered in Bongatech.
     *
     * @var string
     */
    protected $user_id;

    /**
     * password for Bongatech.
     *
     * @var string
     */
    protected $password;

    /**
     * token is generated by md5(password).
     *
     * @var string
     */
    protected $token;

    /**
     * timestamp is the current datetime.
     *
     * @var string
     */
    protected $timestamp;

    /**
     * type of SMS to sent.
     *
     * @var int message
     */
    protected $message_type;

    /**
     * batch type of the SMS being sent.
     *
     * @var int batch
     */
    protected $batch_type;

    /**
     * the alphanumeric of the sender.
     *
     * @var string
     */
    protected $sender_id;

    /**
     * the url on which delivery reports will be sent.
     *
     * @var string callback_url.
     */
    protected $callback_url;


    /**
     * recipient/recipients of the SMS being sent.
     * @var string/array.
     */
    protected $recipients;

    /**
     * the message being sent (array of messages in case message is different for each user.
     *
     * @var string/array.
     */
    protected $message;

    /**
     * Bongatech end point
     *
     * @var string end point.
     */
    protected $endpoint = 'http://197.248.2.55/smsapi_test/submit.php';

    /**
     * SMS constructor.
     * @param string $user_id
     * @param string $password
     * @param string $sender_id
     * @param string $callback_url
     */
    public function __construct($user_id, $password, $sender_id, $callback_url)
    {
        $this->user_id = $user_id;
        $this->password = $password;
        $this->sender_id = $sender_id;
        $this->callback_url = $callback_url;
    }

    /**
     * set the token
     */
    private function setToken()
    {

        $this->token = md5($this->password);
    }

    /**
     * set the timestamp
     */
    private function setTimestamp()
    {

        $this->timestamp = date('YmdHis');
    }

    /**
     * invoke if SMS being sent is of type subscribable.
     *
     * @return $this
     */
    public function subscribable()
    {
        $this->message_type = MessageType::SUBSCIBABLE;

        return $this;
    }

    /**
     * invoke if SMS being sent is of type on demand.
     *
     * @return $this
     */
    public function onDemand()
    {
        $this->message_type = MessageType::ON_DEMAND;

        return $this;
    }

    /**
     * invoke if SMS being sent is of type bulk SMS. This will be the common one.
     * @return $this
     */
    public function bulk()
    {

        $this->message_type = MessageType::BULK;

        return $this;
    }

    /**
     * invoke if SMS is being sent to a single recipient.
     *
     * @return $this
     */
    public function noBatch()
    {

        $this->batch_type = BatchType::NOT_BATCH;

        return $this;
    }

    /**
     * invoke if SMS is being sent to a different recipients.
     *
     * @return $this
     */
    public function sameMessage()
    {

        $this->batch_type = BatchType::SAME_MESSAGE;

        return $this;
    }

    /**
     * invoke if each recipient will receive a different message.
     *
     * @return $this
     */
    public function differentMessages()
    {

        $this->batch_type = BatchType::DIFFERENT_MESSAGE;

        return $this;
    }

    /**
     *
     */
    public function send()
    {
        if ($this->batch_type == BatchType::NOT_BATCH) {

        } elseif ($this->batch_type == BatchType::SAME_MESSAGE) {

        } elseif ($this->batch_type == BatchType::DIFFERENT_MESSAGE) {

        } else {

            throw new BatchTypeNotSetException("Message Batch Type has not been set.");
        }

    }

    /**
     * send a message to a single recipient.
     *
     * @param Request $request
     */
    private function sendForNoBatch(Request $request)
    {
    }

    /**
     * send same message to different recipients.
     *
     * @param Request $request
     */
    private function sendForSameMessage(Request $request)
    {
    }

    /**
     * send different message to different recipients
     *
     * @param Request $request
     */
    private function sendForDifferentMessages(Request $request)
    {
    }


}
